---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install base packages
  apt:
    name:
      - curl
      - nftables
      - docker.io
      - git
      - ca-certificates
      - openssl
    state: present

- name: Enable and start docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Configure nftables
  copy:
    src: "nftables-{{ inventory_hostname }}.conf"
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: "0644"

- name: Enable and start nftables
  systemd:
    name: nftables
    enabled: yes
    state: started
