---
- hosts: all
  become: yes
  roles:
    - role: common

- hosts: vm-auth
  become: yes
  roles:
    - role: auth

- hosts: vm-data
  become: yes
  roles:
    - role: data

- hosts: vm-ingest
  become: yes
  roles:
    - role: ingest

- hosts: vm-core
  become: yes
  roles:
    - role: core

- hosts: vm-app
  become: yes
  roles:
    - role: app

